### ISSUE TITLE
update_ha_state deprecated

### ISSUE THREAD

**Issue by jakebriggs** [lekobob/mitsu_mqtt#1]
update_ha_state has been deprecated, causing the plugin to not work and for this to appear in the logs:
```

8-04-10 22:47:49 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 260, in _async_add_entity
    await entity.async_update_ha_state()
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 222, in async_update_ha_state
    attr = self.state_attributes or {}
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/climate/__init__.py", line 492, in state_attributes
    supported_features = self.supported_features
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/climate/__init__.py", line 775, in supported_features
    raise NotImplementedError()
NotImplementedError
2018-04-10 22:47:50 ERROR (MainThread) [homeassistant.core] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/climate/mitsubishi_mqtt.py", line 99, in message_received
    self.update_ha_state()
AttributeError: 'MqttClimate' object has no attribute 'update_ha_state'
2018-04-10 22:47:50 ERROR (MainThread) [homeassistant.core] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/climate/mitsubishi_mqtt.py", line 99, in message_received
    self.update_ha_state()
AttributeError: 'MqttClimate' object has no attribute 'update_ha_state'
2018-04-10 22:47:50 ERROR (MainThread) [homeassistant.core] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/climate/mitsubishi_mqtt.py", line 99, in message_received
    self.update_ha_state()
AttributeError: 'MqttClimate' object has no attribute 'update_ha_state'
~                                                                             
```

**Comment by joshmcarthur** [comment]
@jakebriggs oh hi! I was able to get this to work more than it used to by seeing what the [parent component does](https://github.com/home-assistant/core/blob/7de3e7d1dd6a88f324b125ad63976eee1feb38cf/homeassistant/components/mqtt/climate.py#L756), and changed `update_ha_state` to `async_write_ha_state()`

**Comment by joshmcarthur** [comment]
I found that in the last couple of years, the built-in HomeAssistant [MQTT Climate integration](https://www.home-assistant.io/integrations/climate.mqtt/) has come along nicely, and can now support the Mitsubishi heatpump with no need of a custom component. 

The YAML configuration takes a bit of fiddling, so I added an example and documented things a bit over at https://github.com/joshmcarthur/homeassistant-climate-mitsubishi-mqtt
